// Códigos SIGPAC de provincias y de los municipios de Almería.
// Fuente: FEGA, https://sigpac-hubcloud.es/codigossigpac/ (provincia.json y municipio4.json).
// Los municipios de otras provincias se descargan cuando hacen falta (ver sigpac.ts).
// Archivo generado: no editar a mano.

export const PROVINCIA_ALMERIA = 4

export const PROVINCIAS: [number, string][] = [
  [1, 'Álava'],
  [2, 'Albacete'],
  [3, 'Alicante'],
  [4, 'Almería'],
  [5, 'Ávila'],
  [6, 'Badajoz'],
  [7, 'Illes Balears'],
  [8, 'Barcelona'],
  [9, 'Burgos'],
  [10, 'Cáceres'],
  [11, 'Cádiz'],
  [12, 'Castellón'],
  [13, 'Ciudad Real'],
  [14, 'Córdoba'],
  [15, 'A Coruña'],
  [16, 'Cuenca'],
  [17, 'Girona'],
  [18, 'Granada'],
  [19, 'Guadalajara'],
  [20, 'Gipuzkoa'],
  [21, 'Huelva'],
  [22, 'Huesca'],
  [23, 'Jaén'],
  [24, 'León'],
  [25, 'Lleida'],
  [26, 'La Rioja'],
  [27, 'Lugo'],
  [28, 'Madrid'],
  [29, 'Málaga'],
  [30, 'Murcia'],
  [31, 'Navarra'],
  [32, 'Ourense'],
  [33, 'Asturias'],
  [34, 'Palencia'],
  [35, 'Las Palmas'],
  [36, 'Pontevedra'],
  [37, 'Salamanca'],
  [38, 'Santa Cruz de Tenerife'],
  [39, 'Cantabria'],
  [40, 'Segovia'],
  [41, 'Sevilla'],
  [42, 'Soria'],
  [43, 'Tarragona'],
  [44, 'Teruel'],
  [45, 'Toledo'],
  [46, 'Valencia'],
  [47, 'Valladolid'],
  [48, 'Bizkaia'],
  [49, 'Zamora'],
  [50, 'Zaragoza'],
]

export const MUNICIPIOS_ALMERIA: [number, string][] = [
  [1, 'Abla'],
  [2, 'Abrucena'],
  [3, 'Adra'],
  [4, 'Albanchez'],
  [5, 'Alboloduy'],
  [6, 'Albox'],
  [7, 'Alcolea'],
  [8, 'Alcóntar'],
  [9, 'Alcudia de Monteagudo'],
  [10, 'Alhabia'],
  [11, 'Alhama de Almería'],
  [12, 'Alicún'],
  [14, 'Almócita'],
  [15, 'Alsodux'],
  [16, 'Antas'],
  [17, 'Arboleas'],
  [18, 'Armuña de Almanzora'],
  [19, 'Bacares'],
  [20, 'Bayárcal'],
  [21, 'Bayarque'],
  [22, 'Bédar'],
  [23, 'Beires'],
  [24, 'Benahadux'],
  [26, 'Benitagla'],
  [27, 'Benizalón'],
  [28, 'Bentarique'],
  [29, 'Berja'],
  [30, 'Canjáyar'],
  [31, 'Cantoria'],
  [32, 'Carboneras'],
  [33, 'Castro de Filabres'],
  [34, 'Cóbdar'],
  [35, 'Cuevas del Almanzora'],
  [36, 'Chercos'],
  [37, 'Chirivel'],
  [38, 'Dalías'],
  [40, 'Las Tres Villas'],
  [41, 'Enix'],
  [43, 'Felix'],
  [44, 'Fines'],
  [45, 'Fiñana'],
  [46, 'Fondón'],
  [47, 'Gádor'],
  [48, 'Los Gallardos'],
  [49, 'Garrucha'],
  [50, 'Gérgal'],
  [51, 'Huécija'],
  [52, 'Huércal de Almería'],
  [53, 'Huércal-Overa'],
  [54, 'Illar'],
  [55, 'Instinción'],
  [56, 'Laroya'],
  [57, 'Laujar de Andarax'],
  [58, 'Líjar'],
  [59, 'Lubrín'],
  [60, 'Lucainena de las Torres'],
  [61, 'Lúcar'],
  [62, 'Macael'],
  [63, 'María'],
  [64, 'Mojácar'],
  [65, 'Nacimiento'],
  [66, 'Níjar'],
  [67, 'Ohanes'],
  [68, 'Olula de Castro'],
  [69, 'Olula del Río'],
  [70, 'Oria'],
  [71, 'Padules'],
  [72, 'Partaloa'],
  [73, 'Paterna del Río'],
  [74, 'Pechina'],
  [75, 'Pulpí'],
  [76, 'Purchena'],
  [77, 'Rágol'],
  [78, 'Rioja'],
  [79, 'Roquetas de Mar'],
  [80, 'Santa Cruz de Marchena'],
  [81, 'Santa Fe de Mondújar'],
  [82, 'Senés'],
  [83, 'Serón'],
  [84, 'Sierro'],
  [85, 'Somontín'],
  [86, 'Sorbas'],
  [87, 'Suflí'],
  [88, 'Tabernas'],
  [89, 'Taberno'],
  [90, 'Tahal'],
  [91, 'Terque'],
  [92, 'Tíjola'],
  [93, 'Turre'],
  [94, 'Turrillas'],
  [95, 'Uleila del Campo'],
  [96, 'Urrácal'],
  [97, 'Velefique'],
  [98, 'Vélez-Blanco'],
  [99, 'Vélez-Rubio'],
  [100, 'Vera'],
  [101, 'Viator'],
  [102, 'Vícar'],
  [103, 'Zurgena'],
  [104, 'El Ejido'],
  [105, 'La Mojonera'],
  [106, 'Balanegra'],
  [900, 'Almería'],
]
